### ISSUE TITLE
coordinate drugs work with the Ben/Andrew/Sebastian/Andra/Gang team

### ISSUE THREAD

**Issue by egonw** [egonw/wikidata2pubchem#3]
Because they are working on PubChem-Wikidata links for drugs.

**Comment by sebotic** [comment]
PubChem RDF already includes links to Wikidata chemical compounds with the predicate 'close match' (http://www.w3.org/2004/02/skos/core#closeMatch). Here would be an example: https://pubchem.ncbi.nlm.nih.gov/rest/rdf/compound/CID42611257

**Comment by egonw** [comment]
OK, great!

This means we should start thinking about matching the two data sources... do the PC2WD mappings match the WD2PC mappings? Are the exactly the same, or is it a "Venn diagram", with both sets having stuff the other set does not have...

(The new WikiPathways RDF also has links to Wikidata (for metabolites, including some drugs), so we're making progress :))

**Comment by sebotic** [comment]
Yes, that's exactly what I have on my plate for the next 2 weeks. I will create an R or iPython notebook and post it as soon as it is ready.

Great to hear that WikiPathyways links ot WD now. Eventually, WikiPathways might even pull compound/metabolite data directly from WD, I had a quick discussion about that with Alex Pico when I met him at a conference back in April.

**Comment by egonw** [comment]
Cool! In R, are you going to use the rcdk package (I hope so)? In case of Python, consider Cinfony, which also can use the CDK... Myself, I was thinking of Bioclipse, but those scripts are harder to share...

Yeah, we've been talking about structure viz for a while now, but lack the resources... for the 2D we (Anders from Alex' group and me) about SVG, e.g. generated with CDKDepict using the SMILES in Wikidata...
